/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.vinicius.appcontrolevencimentos.view;

import br.com.vinicius.appcontrolevencimentos.utilities.UsuariosOnline;
import br.com.vinicius.appcontrolevencimentos.utilities.FecharSistema;
import javax.swing.JFrame;


/**
 *
 * @author FROTA01-PC
 */
public class TelaPrincipal extends javax.swing.JFrame {

    TelaCadastroUsuario telaCadUsuario = new TelaCadastroUsuario();
    UsuariosOnline usuarioOnline = new UsuariosOnline();
    TelaCadastroPerfil telaPerfil = new TelaCadastroPerfil();
    TelaCadastroEmissor telaEmissor = new TelaCadastroEmissor();
    TelaCadastroMotorista telaMotorista = new TelaCadastroMotorista();
    TelaCadastroVeiculo telaVeiculo = new TelaCadastroVeiculo();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {

        initComponents();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanel = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuariosOnline = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        labelTituloStatusDB = new javax.swing.JLabel();
        labelStatusDB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelUsuarioLogado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        menuCadastroEmissor = new javax.swing.JMenuItem();
        menuCadastroDocumento = new javax.swing.JMenuItem();
        menuCadastroLicenca = new javax.swing.JMenuItem();
        menuCadastroVeiculo = new javax.swing.JMenuItem();
        menuCadastroMotorista = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuCadastroUsuario = new javax.swing.JMenuItem();
        menuCadastroPerfil = new javax.swing.JMenuItem();
        menuDocumentos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuLicencas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuOpcoes = new javax.swing.JMenu();
        menuOpcoesSobre = new javax.swing.JMenuItem();
        menuOpcoesAjuda = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuSairSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Vencimentos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuários online:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblUsuariosOnline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usuário"
            }
        ));
        tblUsuariosOnline.setToolTipText("Usuários Online");
        tblUsuariosOnline.setShowGrid(true);
        jScrollPane1.setViewportView(tblUsuariosOnline);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(btnAtualizar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPanel.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPanelLayout = new javax.swing.GroupLayout(desktopPanel);
        desktopPanel.setLayout(desktopPanelLayout);
        desktopPanelLayout.setHorizontalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        desktopPanelLayout.setVerticalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTituloStatusDB.setText("Status DB:");

        labelStatusDB.setText("Online");

        jLabel1.setText("Usuário:");

        labelUsuarioLogado.setText("UsuárioLogado");

        menuCadastros.setText("Cadastros");
        menuCadastros.setName(""); // NOI18N

        menuCadastroEmissor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadastroEmissor.setText("Emissor");
        menuCadastroEmissor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroEmissorActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastroEmissor);

        menuCadastroDocumento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadastroDocumento.setText("Documento");
        menuCadastroDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroDocumentoActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastroDocumento);

        menuCadastroLicenca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadastroLicenca.setText("Licença");
        menuCadastroLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroLicencaActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastroLicenca);

        menuCadastroVeiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadastroVeiculo.setText("Veículo");
        menuCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroVeiculoActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastroVeiculo);

        menuCadastroMotorista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadastroMotorista.setText("Motorista");
        menuCadastroMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroMotoristaActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastroMotorista);
        menuCadastros.add(jSeparator2);

        menuCadastroUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadastroUsuario.setText("Usuário");
        menuCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroUsuarioActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastroUsuario);

        menuCadastroPerfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCadastroPerfil.setText("Perfil");
        menuCadastroPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroPerfilActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastroPerfil);

        jMenuBar1.add(menuCadastros);

        menuDocumentos.setText("Documentos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Veículos");
        menuDocumentos.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem2.setText("Motoristas");
        menuDocumentos.add(jMenuItem2);

        jMenuBar1.add(menuDocumentos);

        menuLicencas.setText("Licenças");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem3.setText("Veículos");
        menuLicencas.add(jMenuItem3);

        jMenuBar1.add(menuLicencas);

        menuRelatorios.setText("Relatórios");
        jMenuBar1.add(menuRelatorios);

        menuOpcoes.setText("Opções");

        menuOpcoesSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuOpcoesSobre.setText("Sobre");
        menuOpcoes.add(menuOpcoesSobre);

        menuOpcoesAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuOpcoesAjuda.setText("Ajuda");
        menuOpcoes.add(menuOpcoesAjuda);

        jMenuBar1.add(menuOpcoes);

        menuSair.setText("Sair");

        menuSairSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuSairSair.setText("Sair");
        menuSairSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairSairActionPerformed(evt);
            }
        });
        menuSair.add(menuSairSair);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloStatusDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStatusDB)
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuarioLogado)
                .addContainerGap(433, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(desktopPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelStatusDB)
                        .addComponent(jLabel1)
                        .addComponent(labelUsuarioLogado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTituloStatusDB)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroDocumentoActionPerformed

    private void menuCadastroLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroLicencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroLicencaActionPerformed

    private void menuSairSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairSairActionPerformed
        // //Ao fechar o sistema, altera o status do usuario
        FecharSistema fechar = new FecharSistema();
        String usuario = labelUsuarioLogado.getText();
        usuarioOnline.alterarStatusOffline(usuarioOnline.buscarIdUsuario(usuario));
        fechar.closeSystem();
    }//GEN-LAST:event_menuSairSairActionPerformed

    private void menuCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroUsuarioActionPerformed
        // TODO add your handling code here:
        telaCadUsuario.setVisible(true);
        desktopPanel.add(telaCadUsuario);
        telaCadUsuario.setPosicao();

    }//GEN-LAST:event_menuCadastroUsuarioActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Ao fechar o sistema, altera o status do usuario:
        String usuario = labelUsuarioLogado.getText();
        usuarioOnline.alterarStatusOffline(usuarioOnline.buscarIdUsuario(usuario));
        System.exit(0);

    }//GEN-LAST:event_formWindowClosing

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:

        usuarioOnline.usuarioOnline();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void menuCadastroEmissorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroEmissorActionPerformed
        // TODO add your handling code here:
        telaEmissor.setVisible(true);
        desktopPanel.add(telaEmissor);
        telaEmissor.setPosicao();
    }//GEN-LAST:event_menuCadastroEmissorActionPerformed

    private void menuCadastroPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroPerfilActionPerformed
        // TODO add your handling code here:
        telaPerfil.setVisible(true);
        desktopPanel.add(telaPerfil);
        telaPerfil.setPosicao();
        
    }//GEN-LAST:event_menuCadastroPerfilActionPerformed

    private void menuCadastroMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroMotoristaActionPerformed
        // TODO add your handling code here:
        telaMotorista.setVisible(true);
        desktopPanel.add(telaMotorista);
        telaMotorista.setPosicao();
    }//GEN-LAST:event_menuCadastroMotoristaActionPerformed

    private void menuCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroVeiculoActionPerformed
        // TODO add your handling code here:
        telaVeiculo.setVisible(true);
        desktopPanel.add(telaVeiculo);
        telaVeiculo.setPosicao();
    }//GEN-LAST:event_menuCadastroVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    public static javax.swing.JDesktopPane desktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    public static javax.swing.JLabel labelStatusDB;
    private javax.swing.JLabel labelTituloStatusDB;
    public static javax.swing.JLabel labelUsuarioLogado;
    private javax.swing.JMenuItem menuCadastroDocumento;
    private javax.swing.JMenuItem menuCadastroEmissor;
    private javax.swing.JMenuItem menuCadastroLicenca;
    private javax.swing.JMenuItem menuCadastroMotorista;
    private javax.swing.JMenuItem menuCadastroPerfil;
    private javax.swing.JMenuItem menuCadastroUsuario;
    private javax.swing.JMenuItem menuCadastroVeiculo;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuDocumentos;
    private javax.swing.JMenu menuLicencas;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenuItem menuOpcoesAjuda;
    private javax.swing.JMenuItem menuOpcoesSobre;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuSairSair;
    public static javax.swing.JTable tblUsuariosOnline;
    // End of variables declaration//GEN-END:variables
}
