/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.vinicius.appcontrolevencimentos.view;

import br.com.vinicius.appcontrolevencimentos.controller.VeiculoDAO;
import br.com.vinicius.appcontrolevencimentos.model.Veiculo;
import br.com.vinicius.appcontrolevencimentos.utilities.LimparCampos;
import br.com.vinicius.appcontrolevencimentos.search.PesquisarSetarVeiculo;
import java.awt.Dimension;
import java.sql.Connection;

/**
 *
 * @author FROTA01-PC
 */
public class TelaCadastroVeiculo extends javax.swing.JInternalFrame {

    PesquisarSetarVeiculo pesquisarVeiculo = new PesquisarSetarVeiculo();
    VeiculoDAO veiculoDAO = new VeiculoDAO();
    Veiculo veiculo = new Veiculo();
    LimparCampos limparCampos = new LimparCampos();
    Connection conexao = null;

    /**
     * Creates new form TelaCadUsuario
     */
    public TelaCadastroVeiculo() {
        initComponents();
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBotaoNovo = new javax.swing.JLabel();
        lblBotaoSalvar = new javax.swing.JLabel();
        lblBotaoCancelar = new javax.swing.JLabel();
        lblBotaoExcluir = new javax.swing.JLabel();
        txtPesquisarVeiculo = new javax.swing.JTextField();
        btnPesquisarVeiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCadastroVeiculo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdVeiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModeloVeiculo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboBottom = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboTipoVeiculo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboAtivo = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Cadastrar Veículo");
        setToolTipText("Cadastrar veículo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBotaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vinicius/appcontrolevencimentos/icons/adicionar-ficheiro.png"))); // NOI18N
        lblBotaoNovo.setToolTipText("Novo");
        lblBotaoNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotaoNovoMouseClicked(evt);
            }
        });

        lblBotaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vinicius/appcontrolevencimentos/icons/salve-.png"))); // NOI18N
        lblBotaoSalvar.setToolTipText("Salvar");
        lblBotaoSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotaoSalvarMouseClicked(evt);
            }
        });

        lblBotaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vinicius/appcontrolevencimentos/icons/cancelar.png"))); // NOI18N
        lblBotaoCancelar.setToolTipText("Cancelar");
        lblBotaoCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotaoCancelarMouseClicked(evt);
            }
        });

        lblBotaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vinicius/appcontrolevencimentos/icons/bin.png"))); // NOI18N
        lblBotaoExcluir.setToolTipText("Excluir");
        lblBotaoExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotaoExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotaoExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBotaoNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBotaoSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBotaoCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBotaoExcluir)
                .addContainerGap(447, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBotaoNovo)
                    .addComponent(lblBotaoSalvar)
                    .addComponent(lblBotaoCancelar)
                    .addComponent(lblBotaoExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtPesquisarVeiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarVeiculoKeyReleased(evt);
            }
        });

        btnPesquisarVeiculo.setText("Pesquisar");
        btnPesquisarVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarVeiculoMouseClicked(evt);
            }
        });

        tblCadastroVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuário", "Senha", "Perfil", "Ativo"
            }
        ));
        tblCadastroVeiculo.setShowGrid(true);
        tblCadastroVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCadastroVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCadastroVeiculo);

        jLabel1.setText("Id:");

        txtIdVeiculo.setEditable(false);
        txtIdVeiculo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Placa:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("Bottom:");

        cboBottom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        jLabel5.setText("Tipo:");

        jLabel6.setText("Ativo:");

        cboAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPesquisarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarVeiculo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                    .addComponent(txtModeloVeiculo)
                                    .addComponent(txtIdVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboAtivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboBottom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboTipoVeiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarVeiculo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtModeloVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setBounds(0, 0, 627, 558);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarVeiculoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarVeiculoKeyReleased
        // TODO add your handling code here:
        pesquisarVeiculo.pesquisarVeiculo();
    }//GEN-LAST:event_txtPesquisarVeiculoKeyReleased

    private void tblCadastroVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCadastroVeiculoMouseClicked
        // TODO add your handling code here:
        pesquisarVeiculo.setarVeiculo();
    }//GEN-LAST:event_tblCadastroVeiculoMouseClicked

    private void lblBotaoCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoCancelarMouseClicked
        // TODO add your handling code here:
        limparCampos.limparCamposVeiculo();
    }//GEN-LAST:event_lblBotaoCancelarMouseClicked

    private void btnPesquisarVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarVeiculoMouseClicked
        // TODO add your handling code here:
        pesquisarVeiculo.pesquisarVeiculo();
    }//GEN-LAST:event_btnPesquisarVeiculoMouseClicked

    private void lblBotaoSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoSalvarMouseClicked
        // TODO add your handling code here:
        if (txtIdVeiculo.getText().isEmpty()) {
            veiculo.setPlaca(txtPlaca.getText());
            veiculo.setModelo(txtModeloVeiculo.getText());
            veiculo.setTipo(pesquisarVeiculo.retornarIdEmissor());
            veiculo.setBottom(cboBottom.getSelectedItem().toString());
            veiculo.setAtivo(cboAtivo.getSelectedItem().toString());
            veiculoDAO.cadastrarVeiculo(veiculo);
        } else {
            veiculo.setPlaca(txtPlaca.getText());
            veiculo.setModelo(txtModeloVeiculo.getText());
            veiculo.setTipo(pesquisarVeiculo.retornarIdEmissor());
            veiculo.setBottom(cboBottom.getSelectedItem().toString());
            veiculo.setAtivo(cboAtivo.getSelectedItem().toString());
            veiculo.setId(Integer.parseInt(txtIdVeiculo.getText()));
            veiculoDAO.editarVeiculo(veiculo);
        }

    }//GEN-LAST:event_lblBotaoSalvarMouseClicked

    private void lblBotaoNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoNovoMouseClicked
        // TODO add your handling code here:
        limparCampos.limparCamposVeiculo();
    }//GEN-LAST:event_lblBotaoNovoMouseClicked

    private void lblBotaoExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoExcluirMouseClicked
        // TODO add your handling code here:
        veiculo.setId(Integer.parseInt(txtIdVeiculo.getText()));
        veiculoDAO.excluirVeiculo(veiculo);
    }//GEN-LAST:event_lblBotaoExcluirMouseClicked

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        cboTipoVeiculo.removeAllItems();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarVeiculo;
    public static javax.swing.JComboBox<String> cboAtivo;
    public static javax.swing.JComboBox<String> cboBottom;
    public static javax.swing.JComboBox<String> cboTipoVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblBotaoCancelar;
    public static javax.swing.JLabel lblBotaoExcluir;
    public static javax.swing.JLabel lblBotaoNovo;
    public static javax.swing.JLabel lblBotaoSalvar;
    public static javax.swing.JTable tblCadastroVeiculo;
    public static javax.swing.JTextField txtIdVeiculo;
    public static javax.swing.JTextField txtModeloVeiculo;
    public static javax.swing.JTextField txtPesquisarVeiculo;
    public static javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
